### ISSUE TITLE
npm run aSite 后报错

### ISSUE THREAD

**Issue by frey-1024** [dennis-jiang/mono-repo-demo#1]
![image](https://user-images.githubusercontent.com/13297317/120881999-92820f80-c607-11eb-90cf-4170b87d2328.png)
![image](https://user-images.githubusercontent.com/13297317/120882014-a62d7600-c607-11eb-98f2-3c69fe0d188b.png)

**Comment by dennis-jiang** [comment]
从报错信息来看，你的依赖应该没有正确安装。
本例使用的是`yarn workspace`，请先运行`yarn`来安装依赖，`npmClient`最好也改为`yarn`。
[具体说明请看这里](https://juejin.cn/post/6913788953971654663#heading-15)
